### ISSUE TITLE
[環境構築] Prettierが効いていなそう

### ISSUE THREAD

**Issue by mizushima1226** [yuki96422/react-todo#1]
Prettierの設定は問題ないかと思いますが、
自分の環境だと、VSCodeで保存した際にPrettierでフォーマットされます
保存時にフォーマットされるように設定しておいた方が良いかと思います〜

↓git cloneしてVSCodeにて保存したところ

https://user-images.githubusercontent.com/47247884/192985449-ce92e847-5888-4643-a18f-b5a954d4ab25.mov

**Comment by yukinobuhara** [comment]
「VSCodeで保存した際にPrettierでフォーマットされる」というのが正しい状態ですか？
自分の環境では、例えば無意味な空白を入れて保存すると空白が削除されて整形されるので、上の状態には該当していると思います。

**Comment by mizushima1226** [comment]
あ、キャプチャした動画がうまく表示されていませんでしたが、
自分の環境ではVSCodeで保存すると、動画のようにフォーマットが走りました
ので、ノブハラさんの環境ではオートフォーマット効いていないのかと思いましたが効いてるんですね👀

確か
```
npm run prettier --write
```
な感じのコマンドでcliからprettierのフォーマット適用できるので、上記コマンドでgitの差分出なければ問題ないかと👍

**Comment by yuki96422** [comment]
すみません、動画で何を検証されているのかがわからないので教えてください。
まずどこでフォーマットが走っているのでしょうか？

動画内では「コメントの下の改行が保存時になくなった」という現象しか見つかりません。
見落としておりましたら申し訳ないのですが、何を検証された結果Prettierが効いていないという判断に至ったのか教えていただけないでしょうか。

自分の環境では、昨日のコメントの通りで無意味な改行を入れて保存すると削除がされるようになっています



https://user-images.githubusercontent.com/109113340/193400517-9f3bc636-d3c9-469d-8a73-9a9b25caf20f.mov

**Comment by mizushima1226** [comment]
TodoList.tsxファイルの11行目の改行が、保存時のフォーマットによって削除されております〜
ただ、ノブハラさんに添付いただいたキャプチャを見ると、AddTodoModalで保存時にフォーマット効いてそうなので、
フォーマット漏れのファイルがいくつかあるようです

react_todoディレクトリに移動して
```
yarn prettier -w . 
```
を実行するとcli経由でフォーマットが実施されます
（自分はパッケージランナーはyarnを使っているので↑で実行できました）
実行方法はここにも記載あったのでリンクだけ共有いたします
https://prettier.io/docs/en/install.html
（↑npmでprettier実行するサンプルない感じなのでおそらくyarnを推奨しているものかと思います）

↓こんな感じでフォーマットによる差分でました〜〜
[![Image from Gyazo](https://i.gyazo.com/e36a3dfec03e860a696fb21bba5d6cc6.jpg)](https://gyazo.com/e36a3dfec03e860a696fb21bba5d6cc6)

**Comment by yuki96422** [comment]
訂正しました。何度もすみませんが、レビューをお願いします
ちなみにフォーマットの漏れはなぜ起こるのでしょうか？

**Comment by mizushima1226** [comment]
修正内容OKです🙆‍♂️

> ちなみにフォーマットの漏れはなぜ起こるのでしょうか？

prettierの設定を入れる前から存在するコードは、設定以降に保存されないとフォーマットされるタイミングがないので
prettier入れた後に
```
yarn prettier -w . 
```
は必ずやるようにしていますね〜

上記以外の原因だと個別具体的に調査が必要かなぁと

後は、huskyやGitHubActionsなどのCIでeslintやprettierのチェックコマンドを実行するようにすると
フォーマット漏れやeslintの警告などの漏れが防止できます〜
ref: https://typicode.github.io/husky/#/
