### ISSUE TITLE
[Bug] Todo一覧をレンダリングする際にkeyが重複しているようです

### ISSUE THREAD

**Issue by mizushima1226** [yuki96422/react-todo#2]
同じタイトルでTodoを登録すると、keyが重複しconsoleに以下のようなエラーが表示されるますー
[![Image from Gyazo](https://i.gyazo.com/acc8ffef428900ae441547eb5fea4b80.png)](https://gyazo.com/acc8ffef428900ae441547eb5fea4b80)

エラー文
```
react_devtools_backend.js:4026 Warning: Encountered two children with the same key, `.0:$test`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

ユーザーが入力した値をkeyに設定されているようなので、一意となるkeyを設定する必要ありそうです〜〜
https://github.com/yuki96422/react-todo/blob/0be59803de2224ee558fe88c774dc9f9136d5f68/react_todo/src/components/pages/TodoList.jsx#L39-L41

実務となるとTodoはデータベースに保存されて一意なIDが割り当てられるので、
`key={id}`とするのが一般的ですが、
今回は簡単に`index`を設定してしまってOKだと思います〜

もう少しこだわるのであれば、todoを登録する際に、以下のようなオブジェクトを作成して配列にpushするといい感じかと思います
```
{
  id: <一意なIDを割り当てる(uuidなど)>
  text: <ここにタイトル>
}
```

Reactのkeyに関して、一応公式ドキュメントのリンクだけ貼っておきますね！
https://ja.reactjs.org/docs/lists-and-keys.html#keys

**Comment by yukinobuhara** [comment]
ありがとうございます
完全にkeyのダブりは失念していました。。
key="index"に変更し、同じtodoを登録してもconsoleのエラー表示がされていないことを確認しました。

<img width="1183" alt="スクリーンショット 2022-09-30 20 34 40" src="https://user-images.githubusercontent.com/113037997/193261195-769ebd6f-1907-4113-84f9-978f0b41b81d.png">

**Comment by mizushima1226** [comment]
あ、文字列で`"index"`指定してしまうと全てのkeyが`index`で割り当てられてしまうので結局重複してしまいます〜
↓ローカルで試しましたがwarning解消されていないようです👀
[![Image from Gyazo](https://i.gyazo.com/4d7c9a661f3681599ab4f85eb0906b9d.png)](https://gyazo.com/4d7c9a661f3681599ab4f85eb0906b9d)


mapのコールバック関数の第２引数でindex取っているので、これを指定する感じです〜↓↓↓
```
{incompleteTodo.map((todo, index) => ( 
     <TodoCard 
```

**Comment by mizushima1226** [comment]
[indexを修正](https://github.com/yuki96422/react-todo/commit/87aecaa719bb7f515e43d6bdc922f81bff24ebb7)

良きと思います〜👍
