### ISSUE TITLE
[微修正] 変数の命名がパスカルケースになっている

### ISSUE THREAD

**Issue by mizushima1226** [yuki96422/react-todo#3]
以下の２箇所ですが、変数がパスカルケースで命名されているようです〜
jsの命名規則でいくと、変数の命名はキャメルケースが一般的なのでこの機会に覚えておいてもらえると👍だと思います

https://github.com/yuki96422/react-todo/blob/0be59803de2224ee558fe88c774dc9f9136d5f68/react_todo/src/components/providers/InCompleteTodoProvider.jsx#L8

https://github.com/yuki96422/react-todo/blob/0be59803de2224ee558fe88c774dc9f9136d5f68/react_todo/src/components/providers/CompleteTodoProvider.jsx#L8

Reactのコンポーネントは、Reactのルール上、パスカルケースで命名することになっているので少しややこしいですね😓

**Comment by yukinobuhara** [comment]
ありがとうございます。混同していたので大変助かりました！
JS→キャメルケース
React→パスカルケース　ですね、気をつけます。修正もしました。

**Comment by mizushima1226** [comment]
修正確認できました！🙌
