### ISSUE TITLE
[改善] ボタンコンポーネントの実装について

### ISSUE THREAD

**Issue by mizushima1226** [yuki96422/react-todo#4]
全体的にいい感じにコンポーネント作れていると思います🎉

ボタンコンポーネントに関して改善の余地ありそうでしたのでissueあげてみました〜

現状、以下のボタンコンポーネントが実装されています
- AddTodoButton
- CancelTodoButton
- CircleButton
- MainButton

上3つのコンポーネントは「追加ボタン」「キャンセルボタン」「サークルボタン（プラスボタン）」のように
用途がかなり限られたコンポーネントになっているので、汎用性が低くなっています〜

ので改善すると
- MainButton
- CircleButton
の2つだけでまかなえそうです

## CircleButtonについて
今の実装だと、プラスアイコン以外のアイコンを使いたい場合、別のコンポーネントを実装することになるかと思います
MainButtonのようにchildrenを受け取るような実装にすると、CircleButtonコンポーネントだけで様々なアイコンを表示できるようになります💡

以下のような使用イメージです
```
<CircleButton>
  <Icon >
</CircleButton>
```

## その他のボタンコンポーネントについて
propsをうまく駆使すると、MainButtonコンポーネントを改善するだけで、
AddTodoButton/CancelTodoButtonコンポーネントが不要になります

MainButtonコンポーネントはpropsで
- bgColor
- children
- onClick
を受け取るようなイメージです

_hoverにて配色を指定していますが、opacityを使ってあげれば、どんな色でも薄めのデザインを表現できるかと思います〜
↑のような実装にすると汎用性の高いコンポーネントになってメンテナンスしやすくなります

ざっくりした実装イメージを書いてみましたが、対応する際に困ることあれば都度ご相談くださいませ〜

## 補足
今回話題になったボタンコンポーネントで、いろんな画面での使用が想定されるコンポーネントだと思います
ので、汎用性を重視した実装をしておくと良い感じです

TodoCardのような、様々なコンポーネントを組み合わせた複雑なUIを1つのコンポーネントにまとめるようなこともよくあり、
意味のある単位でひとまとまりのコンポーネントとして整理しておくことでコードの見通しが良くなる
といったこともあるので汎用性とはまた違った観点でのコンポーネントの切り出し方もあります〜〜

考え方の参考になればです🙌

**Comment by yuki96422** [comment]
ありがとうございます！
確かにボタンも汎用性低い実装にしていたので修正しました
おそらく実装できていると思いますが、念の為ご確認お願いします🙏

**Comment by mizushima1226** [comment]
お〜〜いい感じです！！ナイスです！！
