### ISSUE TITLE
useEffectの依存配列について

### ISSUE THREAD

**Issue by mizushima1226** [yuki96422/react-todo#5]
ここの実装、無限ループに陥るような実装になってますね〜💡
https://github.com/yuki96422/react-todo/blob/0cb932d308be413004c32da8d4c0fdfd23eeb85e/react_todo/src/components/popup/AddTodoModal.jsx#L25-L27

今回は`initialTodo`が文字列（プリミティブ型のデータ）なので問題は顕在化していませんが
オブジェクト型のデータだとuseEffectの処理が無限ループします

この無限ループが
リクエスト量に応じて課金されるAPI
だったり
データベースに変更が加わるAPI(商品を購入するAPIなど）
の場合、かなりリスキーな実装になっていることがわかると思います〜
（後者のような実装はそもそもあまり考えられないですが）

なので、useEffectの依存変数の指定は注意が必要ですので、今回の件をきっかけに覚えておくと良いと思います👍

試しに
https://github.com/yuki96422/react-todo/blob/0cb932d308be413004c32da8d4c0fdfd23eeb85e/react_todo/src/hooks/useInitialTodo.jsx#L6-L10

のステートの更新部分を
```
setInitialTodo({todoTitle});
```
のように文字列ではなくオブジェクトとして更新してみてください〜
useEffectの処理が無限ループするはずです
chromeのdevtoolsのnetworkタブで無限にリクエストされることが確認できると思います

↑で無限ループしないような実装にしてみたくださいませ〜🚀

**Comment by yuki96422** [comment]
ありがとうございます。
実際にステートの更新部分をオブジェクトとして更新したところ、無限ループが発生することを確認しました。

要因がわからないのですが、なぜでしょうか？

自分の理解では
　Add Todo Moadl.jsx内のuseEffectの第二引数に渡しているinitialTodoは
useCallbackでラップされたgetTodoの実行結果なので、初回レンダリング時のみ実行される
⇨すなわち無限ループは起こらないと認識しています

**Comment by mizushima1226** [comment]
> useCallbackでラップされたgetTodo

これはあくまでも、getTodoがメモ化されているだけです

依存変数に`initialTodo`を指定しているので、
`initialTodo`の変更を検知するたびに、useEffectの処理が発火します

getTodoをどのタイミングで実行したいか？
それを実現するためには依存変数をどうのように指定したら良いか？
あたりですね💡

**Comment by yuki96422** [comment]
ありがとうございます。
初回マウント時のみに実行させたいので、第二引数を空配列としました。
再度レビューをお願いします

**Comment by mizushima1226** [comment]
良きと思います🙆‍♂️
このissueはcloseしますね🙌
